---
- name: AWS role
  ansible.builtin.import_role:
    name: inqwise.common.aws
  vars:
    dns_record_list:
    - name: "{{ private_dns }}.{{ private_domain }}"
      zone: "{{ private_domain }}"
      type: A
      value: "{{ private_ip }}"
      private: true
      ttl: 120
    tags_facts:
      private_dns: "private_dns"
      _replicaof: "_replicaof"
      _data_snapshot: "_data_snapshot"
  
- name: Redis role
  ansible.builtin.import_role:
    name: inqwise.stacktrek.redis